export enum RolesType {
  //ADMIN
  ADMIN = 'ADMIN',
  OPERATOR = 'OPERATOR',

  //COMPANY
  ADMIN_COMPANY = 'ADMIN_COMPANY',
  OPERATOR_COMPANY = 'OPERATOR_COMPANY',
  DRIVER_COMPANY = 'DRIVER_COMPANY',
}
